[package]
name = "slicket-store"
version.workspace = true
edition.workspace = true

[dependencies]
slicket-core = { version = "0.1.0", path = "../slicket-core" }
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio", "postgres", "macros", "migrate"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
